OrdererOrgs:
  - Name: Orderer
    Domain: thermotrace.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer1
      - Hostname: orderer2
      - Hostname: orderer3

PeerOrgs:
  - Name: MROLab
    Domain: mrolab.thermotrace.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2

  - Name: Manufacturer
    Domain: manufacturer.thermotrace.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 2
